# Generated by Django 3.0.2 on 2020-04-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200419_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='user_name',
            new_name='username',
        ),
    ]
