# Generated by Django 3.0.2 on 2020-04-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200419_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='mobno',
            field=models.IntegerField(),
        ),
    ]
