# Generated by Django 3.0.2 on 2020-04-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200419_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(default='denied', max_length=10),
        ),
    ]
