# Generated by Django 3.0.2 on 2020-04-20 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20200420_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Store'),
        ),
    ]
