# Generated by Django 3.0.2 on 2020-04-22 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20200421_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='name',
            new_name='bill',
        ),
        migrations.AlterField(
            model_name='bill',
            name='sname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Store'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Store'),
        ),
    ]
